### ISSUE TITLE
No snapshot jpg file running on local Windows laptop

### ISSUE THREAD

**Issue by rsiu0104** [alwaysai/snapshot-security-camera#2]
I have trying out the SnapShot Secuirty Camera App on my local windows laptop. However, I don't see the snapshot jpg files written to my project directory.

**Comment by ericvanbuhler** [comment]
Hi @rsiu0104,

Are you seeing the app detect any people in the Streamer web interface? Images only get generated when a person is detected. If the app is detecting people, can you add this print statement in the `save_snapshot()` function and share the logs?

```
print('Saving image: {}'.format(filename))
```

**Comment by rsiu0104** [comment]
The app is able to detect people. After adding print statement, the console shows the filename.

I was able to deploy the app to my Jetson Nano and the file are generated in the Nano's project directory. However, when I run it locally, it does not generate it on my local Windows laptop. I think this can be easily replicated.

**Comment by ericvanbuhler** [comment]
Cool, I'll try to reproduce this on Windows. Are you running Windows 10?

**Comment by ericvanbuhler** [comment]
I was able to reproduce the issue, and determine that it was due to the image filename container invalid characters for Windows, specifically ':'. I replaced them with '.' on the branch https://github.com/alwaysai/snapshot-security-camera/compare/bugfix/file-name-for-windows. Can you try out that branch and let me know if the issue is resolved for you?
